### ISSUE TITLE
Git Guide - Feedback

### ISSUE THREAD

**Issue by fleeting** [Monkee-Boy/mbGuides#1]
This guide can be found at [general/git](http://guides.dev.monkee-boy.com/content/general/git.html) with the file at [git.md](https://github.com/Monkee-Boy/mbGuides/blob/master/general/git.md).

This is out of draft phase and pending final feedback and approval from the team.

@smhigley @defvayne23 @pgautier404 @jesscanales

**Comment by fleeting** [comment]
@defvayne23 Any suggestions or feedback regarding the `git` guide? If nothing else, I'll mark it as approved.

**Comment by defvayne23** [comment]
:+1:
